version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reportnewsservice
    ports:
      - "8080:8080"       # Если твой сервис слушает на 8080
    environment:
      - NATS_URL=nats://nats:4222
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - nats
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
