// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/delivery/grpc/proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Notification) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Notification) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Notification) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Notification) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type NotificationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationId) Reset() {
	*x = NotificationId{}
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationId) ProtoMessage() {}

func (x *NotificationId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationId.ProtoReflect.Descriptor instead.
func (*NotificationId) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP(), []int{2}
}

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNotificationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateNotificationRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CreateNotificationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateNotificationRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateNotificationRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type UpdateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNotificationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateNotificationRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *UpdateNotificationRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateNotificationRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateNotificationRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	DateFrom      int64                  `protobuf:"varint,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        int64                  `protobuf:"varint,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListNotificationsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListNotificationsRequest) GetDateFrom() int64 {
	if x != nil {
		return x.DateFrom
	}
	return 0
}

func (x *ListNotificationsRequest) GetDateTo() int64 {
	if x != nil {
		return x.DateTo
	}
	return 0
}

type Notifications struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Notification        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notifications) Reset() {
	*x = Notifications{}
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notifications) ProtoMessage() {}

func (x *Notifications) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_proto_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notifications.ProtoReflect.Descriptor instead.
func (*Notifications) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *Notifications) GetItems() []*Notification {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_delivery_grpc_proto_notification_proto protoreflect.FileDescriptor

const file_internal_delivery_grpc_proto_notification_proto_rawDesc = "" +
	"\n" +
	"/internal/delivery/grpc/proto/notification.proto\x12\fnotification\"\xf0\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\" \n" +
	"\x0eNotificationId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty\"\xce\x01\n" +
	"\x19CreateNotificationRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\"\xde\x01\n" +
	"\x19UpdateNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\"\x91\x01\n" +
	"\x18ListNotificationsRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1b\n" +
	"\tdate_from\x18\x03 \x01(\x03R\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x04 \x01(\x03R\x06dateTo\"A\n" +
	"\rNotifications\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.notification.NotificationR\x05items2\xde\a\n" +
	"\x13NotificationService\x12Y\n" +
	"\x12CreateNotification\x12'.notification.CreateNotificationRequest\x1a\x1a.notification.Notification\x12K\n" +
	"\x0fGetNotification\x12\x1c.notification.NotificationId\x1a\x1a.notification.Notification\x12X\n" +
	"\x11ListNotifications\x12&.notification.ListNotificationsRequest\x1a\x1b.notification.Notifications\x12Y\n" +
	"\x12UpdateNotification\x12'.notification.UpdateNotificationRequest\x1a\x1a.notification.Notification\x12G\n" +
	"\x12DeleteNotification\x12\x1c.notification.NotificationId\x1a\x13.notification.Empty\x12]\n" +
	"\x16GetNotificationsByDate\x12&.notification.ListNotificationsRequest\x1a\x1b.notification.Notifications\x12a\n" +
	"\x1aGetNotificationsByLocation\x12&.notification.ListNotificationsRequest\x1a\x1b.notification.Notifications\x12a\n" +
	"\x1aGetNotificationsByResource\x12&.notification.ListNotificationsRequest\x1a\x1b.notification.Notifications\x127\n" +
	"\vHealthCheck\x12\x13.notification.Empty\x1a\x13.notification.Empty\x120\n" +
	"\x04Ping\x12\x13.notification.Empty\x1a\x13.notification.Empty\x12K\n" +
	"\x16SubscribeNotifications\x12\x13.notification.Empty\x1a\x1a.notification.Notification0\x01\x12D\n" +
	"\x0fAckNotification\x12\x1c.notification.NotificationId\x1a\x13.notification.EmptyBDZBgithub.com/erazz/outage-service/internal/delivery/grpc/proto;protob\x06proto3"

var (
	file_internal_delivery_grpc_proto_notification_proto_rawDescOnce sync.Once
	file_internal_delivery_grpc_proto_notification_proto_rawDescData []byte
)

func file_internal_delivery_grpc_proto_notification_proto_rawDescGZIP() []byte {
	file_internal_delivery_grpc_proto_notification_proto_rawDescOnce.Do(func() {
		file_internal_delivery_grpc_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_proto_notification_proto_rawDesc), len(file_internal_delivery_grpc_proto_notification_proto_rawDesc)))
	})
	return file_internal_delivery_grpc_proto_notification_proto_rawDescData
}

var file_internal_delivery_grpc_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_delivery_grpc_proto_notification_proto_goTypes = []any{
	(*Notification)(nil),              // 0: notification.Notification
	(*NotificationId)(nil),            // 1: notification.NotificationId
	(*Empty)(nil),                     // 2: notification.Empty
	(*CreateNotificationRequest)(nil), // 3: notification.CreateNotificationRequest
	(*UpdateNotificationRequest)(nil), // 4: notification.UpdateNotificationRequest
	(*ListNotificationsRequest)(nil),  // 5: notification.ListNotificationsRequest
	(*Notifications)(nil),             // 6: notification.Notifications
}
var file_internal_delivery_grpc_proto_notification_proto_depIdxs = []int32{
	0,  // 0: notification.Notifications.items:type_name -> notification.Notification
	3,  // 1: notification.NotificationService.CreateNotification:input_type -> notification.CreateNotificationRequest
	1,  // 2: notification.NotificationService.GetNotification:input_type -> notification.NotificationId
	5,  // 3: notification.NotificationService.ListNotifications:input_type -> notification.ListNotificationsRequest
	4,  // 4: notification.NotificationService.UpdateNotification:input_type -> notification.UpdateNotificationRequest
	1,  // 5: notification.NotificationService.DeleteNotification:input_type -> notification.NotificationId
	5,  // 6: notification.NotificationService.GetNotificationsByDate:input_type -> notification.ListNotificationsRequest
	5,  // 7: notification.NotificationService.GetNotificationsByLocation:input_type -> notification.ListNotificationsRequest
	5,  // 8: notification.NotificationService.GetNotificationsByResource:input_type -> notification.ListNotificationsRequest
	2,  // 9: notification.NotificationService.HealthCheck:input_type -> notification.Empty
	2,  // 10: notification.NotificationService.Ping:input_type -> notification.Empty
	2,  // 11: notification.NotificationService.SubscribeNotifications:input_type -> notification.Empty
	1,  // 12: notification.NotificationService.AckNotification:input_type -> notification.NotificationId
	0,  // 13: notification.NotificationService.CreateNotification:output_type -> notification.Notification
	0,  // 14: notification.NotificationService.GetNotification:output_type -> notification.Notification
	6,  // 15: notification.NotificationService.ListNotifications:output_type -> notification.Notifications
	0,  // 16: notification.NotificationService.UpdateNotification:output_type -> notification.Notification
	2,  // 17: notification.NotificationService.DeleteNotification:output_type -> notification.Empty
	6,  // 18: notification.NotificationService.GetNotificationsByDate:output_type -> notification.Notifications
	6,  // 19: notification.NotificationService.GetNotificationsByLocation:output_type -> notification.Notifications
	6,  // 20: notification.NotificationService.GetNotificationsByResource:output_type -> notification.Notifications
	2,  // 21: notification.NotificationService.HealthCheck:output_type -> notification.Empty
	2,  // 22: notification.NotificationService.Ping:output_type -> notification.Empty
	0,  // 23: notification.NotificationService.SubscribeNotifications:output_type -> notification.Notification
	2,  // 24: notification.NotificationService.AckNotification:output_type -> notification.Empty
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_delivery_grpc_proto_notification_proto_init() }
func file_internal_delivery_grpc_proto_notification_proto_init() {
	if File_internal_delivery_grpc_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_proto_notification_proto_rawDesc), len(file_internal_delivery_grpc_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_delivery_grpc_proto_notification_proto_goTypes,
		DependencyIndexes: file_internal_delivery_grpc_proto_notification_proto_depIdxs,
		MessageInfos:      file_internal_delivery_grpc_proto_notification_proto_msgTypes,
	}.Build()
	File_internal_delivery_grpc_proto_notification_proto = out.File
	file_internal_delivery_grpc_proto_notification_proto_goTypes = nil
	file_internal_delivery_grpc_proto_notification_proto_depIdxs = nil
}
